***************
*** 116,123 ****
  asflags-y := -Wa,-march=all
  
  # Supply kernel BSS size to the decompressor via a linker symbol.
- KBSS_SZ = $(shell size $(obj)/../../../../vmlinux | awk 'END{print $$3}')
  LDFLAGS_vmlinux = --defsym _kernel_bss_size=$(KBSS_SZ)
  # Supply ZRELADDR to the decompressor via a linker symbol.
  ifneq ($(CONFIG_AUTO_ZRELADDR),y)
  
--- 116,126 ----
  asflags-y := -Wa,-march=all
  
  # Supply kernel BSS size to the decompressor via a linker symbol.
+ KBSS_SZ = $(shell if $(CROSS_COMPILE)size $(obj)/../../../../vmlinux; then :; \
+ 		else size $(obj)/../../../../vmlinux; fi | awk 'END{print $$3}')
+ ifneq ($(KBSS_SZ),)
  LDFLAGS_vmlinux = --defsym _kernel_bss_size=$(KBSS_SZ)
+ endif
  # Supply ZRELADDR to the decompressor via a linker symbol.
  ifneq ($(CONFIG_AUTO_ZRELADDR),y)
  
